name: Reusablke Workflow
on:
  workflow_call:
    inputs:
      name: 
        description: 'Input description'
        type: string
        default: 'VÃ­ctor'
        required: false
    secrets:
      access-token: 
        description: 'Secret description'
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display Github Context
        run: echo '${{ toJSON(github) }}'
      - name: Display name inputs
        run: echo '${{ inputs.name }}'
      - name: Display access-token secret
        run: echo '${{ secrets.access-token }}'